### ISSUE TITLE
Actividad 5. Cuadro comparativo 1BS

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-AdriHernandez-Martinez0863#1]
[Actividad 5. Cuadro comparativo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-AdriHernandez-Martinez0863/files/9651650/Actividad.5.Cuadro.comparativo.pdf)

**Comment by Jaczibeth** [comment]
Obtuviste 18% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
